// src/lib/cigano-cards-data.ts

export const ciganoCards = [
    { id: 1, name: "O Cavaleiro", image: "/taro/cavaleiro.png", keywords: "movimento novidades" },
    { id: 2, name: "O Trevo", image: "/taro/trevo.png", keywords: "sorte contratempos" },
    { id: 3, name: "O Navio", image: "/taro/navio.png", keywords: "mudancas viagens" },
    { id: 4, name: "A Casa", image: "/taro/casa.png", keywords: "estabilidade familia" },
    { id: 5, name: "A Árvore", image: "/taro/arvore.png", keywords: "saude ancestralidade" },
    { id: 6, name: "As Nuvens", image: "/taro/nuvens.png", keywords: "confusao clareza" },
    { id: 7, name: "A Serpente", image: "/taro/serpente.png", keywords: "mentiras renovacao" },
    { id: 8, name: "O Caixão", image: "/taro/caixao.png", keywords: "encerramento ciclos" },
    { id: 9, name: "O Buquê", image: "/taro/buque.png", keywords: "criatividade alegria" },
    { id: 10, name: "A Foice", image: "/taro/foice.png", keywords: "cortes colheita" },
    { id: 11, name: "O Chicote", image: "/taro/chicote.png", keywords: "brigas energia" },
    { id: 12, name: "Os Pássaros", image: "/taro/passaros.png", keywords: "comunicacao leveza" },
    { id: 13, name: "A Criança", image: "/taro/criança.png", keywords: "espontaneidade imaturidade" },
    { id: 14, name: "A Raposa", image: "/taro/raposa.png", keywords: "estrategia cautela" },
    { id: 15, name: "O Urso", image: "/taro/urso.png", keywords: "superprotecao apego" },
    { id: 16, name: "A Estrela", image: "/taro/estrela.png", keywords: "proposito destino" },
    { id: 17, name: "A Cegonha", image: "/taro/cegonha.png", keywords: "cocriacao novidades" },
    { id: 18, name: "O Cão", image: "/taro/cao.png", keywords: "companheirismo lealdade" },
    { id: 19, name: "A Torre", image: "/taro/torre.png", keywords: "autoconhecimento distanciamento" },
    { id: 20, name: "O Jardim", image: "/taro/jardim.png", keywords: "vida social" },
    { id: 21, name: "A Montanha", image: "/taro/montanha.png", keywords: "desafios obstaculos" },
    { id: 22, name: "O Caminho", image: "/taro/caminho.png", keywords: "decisoes escolhas" },
    { id: 23, name: "O Rato", image: "/taro/rato.png", keywords: "desgaste perdas" },
    { id: 24, name: "O Coração", image: "/taro/coração.png", keywords: "amor genuino" },
    { id: 25, name: "O Anel", image: "/taro/anel.png", keywords: "compromissos ligacao" },
    { id: 26, name: "Os Livros", image: "/taro/livros.png", keywords: "estudos segredos" },
    { id: 27, name: "A Carta", image: "/taro/carta.png", keywords: "comunicacao contratos" },
    { id: 28, name: "O Cigano", image: "/taro/cigano.png", keywords: "homem consulente" },
    { id: 29, name: "A Cigana", image: "/taro/cigana.png", keywords: "mulher consulente" },
    { id: 30, name: "Os Lírios", image: "/taro/lirios.png", keywords: "paz tranquilidade" },
    { id: 31, name: "O Sol", image: "/taro/sol.png", keywords: "alegria brilho" },
    { id: 32, name: "A Lua", image: "/taro/lua.png", keywords: "emocoes interior" },
    { id: 33, name: "A Chave", image: "/taro/chave.png", keywords: "solucoes oportunidades" },
    { id: 34, name: "Os Peixes", image: "/taro/peixes.png", keywords: "dinheiro abundancia" },
    { id: 35, name: "A Âncora", image: "/taro/ancora.png", keywords: "firmeza seguranca" },
    { id: 36, name: "A Cruz", image: "/taro/cruz.png", keywords: "vitoria peso" },
];
