// src/lib/cigano-cards-data.ts

export const ciganoCards = [
    { id: 1, name: "O Cavaleiro", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "movimento novidades" },
    { id: 2, name: "O Trevo", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "sorte contratempos" },
    { id: 3, name: "O Navio", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "mudancas viagens" },
    { id: 4, name: "A Casa", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "estabilidade familia" },
    { id: 5, name: "A Árvore", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "saude ancestralidade" },
    { id: 6, name: "As Nuvens", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "confusao clareza" },
    { id: 7, name: "A Serpente", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "mentiras renovacao" },
    { id: 8, name: "O Caixão", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "encerramento ciclos" },
    { id: 9, name: "O Buquê", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "criatividade alegria" },
    { id: 10, name: "A Foice", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "cortes colheita" },
    { id: 11, name: "O Chicote", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "brigas energia" },
    { id: 12, name: "Os Pássaros", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "comunicacao leveza" },
    { id: 13, name: "A Criança", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "espontaneidade imaturidade" },
    { id: 14, name: "A Raposa", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "estrategia cautela" },
    { id: 15, name: "O Urso", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "superprotecao apego" },
    { id: 16, name: "A Estrela", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "proposito destino" },
    { id: 17, name: "A Cegonha", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "cocriacao novidades" },
    { id: 18, name: "O Cão", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "companheirismo lealdade" },
    { id: 19, name: "A Torre", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "autoconhecimento distanciamento" },
    { id: 20, name: "O Jardim", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "vida social" },
    { id: 21, name: "A Montanha", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "desafios obstaculos" },
    { id: 22, name: "O Caminho", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "decisoes escolhas" },
    { id: 23, name: "O Rato", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "desgaste perdas" },
    { id: 24, name: "O Coração", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "amor genuino" },
    { id: 25, name: "O Anel", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "compromissos ligacao" },
    { id: 26, name: "Os Livros", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "estudos segredos" },
    { id: 27, name: "A Carta", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "comunicacao contratos" },
    { id: 28, name: "O Homem", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "homem consulente" },
    { id: 29, name: "A Mulher", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "mulher consulente" },
    { id: 30, name: "Os Lírios", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "paz tranquilidade" },
    { id: 31, name: "O Sol", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "alegria brilho" },
    { id: 32, name: "A Lua", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "emocoes interior" },
    { id: 33, name: "A Chave", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "solucoes oportunidades" },
    { id: 34, name: "Os Peixes", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "dinheiro abundancia" },
    { id: 35, name: "A Âncora", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "firmeza seguranca" },
    { id: 36, name: "A Cruz", image: "https://placehold.co/200x300/1a1a2e/ffffff.png", keywords: "vitoria peso" },
];
