// src/lib/cigano-cards-data.ts

export const ciganoCards = [
    { id: 1, name: "O Cavaleiro", image: "https://placehold.co/200x300.png", keywords: "noticias movimento exu" },
    { id: 2, name: "O Trevo", image: "https://placehold.co/200x300.png", keywords: "sorte obstaculos caboclos" },
    { id: 3, name: "O Navio", image: "https://placehold.co/200x300.png", keywords: "viagem mudanca iemanja" },
    { id: 4, name: "A Casa", image: "https://placehold.co/200x300.png", keywords: "familia estabilidade" },
    { id: 5, name: "A Árvore", image: "https://placehold.co/200x300.png", keywords: "saude crescimento" },
    { id: 6, name: "As Nuvens", image: "https://placehold.co/200x300.png", keywords: "duvidas confusao" },
    { id: 7, name: "A Serpente", image: "https://placehold.co/200x300.png", keywords: "traicao sabedoria" },
    { id: 8, name: "O Caixão", image: "https://placehold.co/200x300.png", keywords: "fim transformacao" },
    { id: 9, name: "O Buquê", image: "https://placehold.co/200x300.png", keywords: "alegria presente" },
    { id: 10, name: "A Foice", image: "https://placehold.co/200x300.png", keywords: "corte decisao" },
    { id: 11, name: "O Chicote", image: "https://placehold.co/200x300.png", keywords: "discussao energia" },
    { id: 12, name: "Os Pássaros", image: "https://placehold.co/200x300.png", keywords: "comunicacao fofoca" },
    { id: 13, name: "A Criança", image: "https://placehold.co/200x300.png", keywords: "inocencia novo" },
    { id: 14, name: "A Raposa", image: "https://placehold.co/200x300.png", keywords: "astucia trabalho" },
    { id: 15, name: "O Urso", image: "https://placehold.co/200x300.png", keywords: "forca ciumes" },
    { id: 16, name: "A Estrela", image: "https://placehold.co/200x300.png", keywords: "sucesso espiritualidade" },
    { id: 17, name: "A Cegonha", image: "https://placehold.co/200x300.png", keywords: "novidades mudancas" },
    { id: 18, name: "O Cachorro", image: "https://placehold.co/200x300.png", keywords: "amizade lealdade" },
    { id: 19, name: "A Torre", image: "https://placehold.co/200x300.png", keywords: "isolamento espiritualidade" },
    { id: 20, name: "O Jardim", image: "https://placehold.co/200x300.png", keywords: "publico social" },
    { id: 21, name: "A Montanha", image: "https://placehold.co/200x300.png", keywords: "desafios justica" },
    { id: 22, name: "Os Caminhos", image: "https://placehold.co/200x300.png", keywords: "escolhas decisoes" },
    { id: 23, name: "Os Ratos", image: "https://placehold.co/200x300.png", keywords: "perdas desgaste" },
    { id: 24, name: "O Coração", image: "https://placehold.co/200x300.png", keywords: "amor paixao" },
    { id: 25, name: "O Anel", image: "https://placehold.co/200x300.png", keywords: "uniao relacionamento" },
    { id: 26, name: "Os Livros", image: "https://placehold.co/200x300.png", keywords: "segredos estudo" },
    { id: 27, name: "A Carta", image: "https://placehold.co/200x300.png", keywords: "noticias comunicacao" },
    { id: 28, name: "O Homem", image: "https://placehold.co/200x300.png", keywords: "homem consulente" },
    { id: 29, name: "A Mulher", image: "https://placehold.co/200x300.png", keywords: "mulher consulente" },
    { id: 30, name: "Os Lírios", image: "https://placehold.co/200x300.png", keywords: "paz harmonia" },
    { id: 31, name: "O Sol", image: "https://placehold.co/200x300.png", keywords: "sucesso energia" },
    { id: 32, name: "A Lua", image: "https://placehold.co/200x300.png", keywords: "intuicao reconhecimento" },
    { id: 33, name: "A Chave", image: "https://placehold.co/200x300.png", keywords: "solucoes sucesso" },
    { id: 34, name: "Os Peixes", image: "https://placehold.co/200x300.png", keywords: "dinheiro prosperidade" },
    { id: 35, name: "A Âncora", image: "https://placehold.co/200x300.png", keywords: "seguranca estabilidade" },
    { id: 36, name: "A Cruz", image: "https://placehold.co/200x300.png", keywords: "vitoria destino" },
];
