
// Import the functions you need from the SDKs you need
import { initializeApp, getApps, getApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
// import { getFirestore, type Firestore } from 'firebase/firestore'; // Descomente se você precisar do Firestore
import { getDatabase, type Database } from 'firebase/database'; // Adicionado para Realtime Database

// Your web app's Firebase configuration (TEMPORARILY HARDCODED FOR DIAGNOSTICS)
const firebaseConfig = {
  apiKey: "AIzaSyBq2Zl5_Fw4ii3SAPA-XaXUbjDTVpxJA8s",
  authDomain: "mystic-insights-g3d6e.firebaseapp.com",
  databaseURL: "https://mystic-insights-g3d6e-default-rtdb.firebaseio.com", // Ensure no trailing slash
  projectId: "mystic-insights-g3d6e",
  storageBucket: "mystic-insights-g3d6e.appspot.com", // Using .appspot.com as commonly generated by Firebase. If firebasestorage.app is correct, update here.
  messagingSenderId: "532385647325",
  appId: "1:532385647325:web:18dbe9cd46a9cce8256934"
  // measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID // Descomente se você usar o Analytics
};

// Initialize Firebase
let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const auth: Auth = getAuth(app);
// const firestoreDb: Firestore = getFirestore(app); // Descomente se você precisar do Firestore
const rtdb: Database = getDatabase(app); // Inicializa o Realtime Database

export { app, auth, rtdb /*, firestoreDb */ };
