// src/lib/yidams-data.ts

export const yidams = [
    { name: "Chenrezig (Avalokiteshvara)", symbolicRepresentation: "Flor de lótus branca", symbolicMeaning: "Compaixão pura", symbolicImage: "Lótus branco nas mãos, mil braços, olhos ternos" },
    { name: "Tara Verde", symbolicRepresentation: "Selo de oito pétalas", symbolicMeaning: "Ação compassiva e proteção", symbolicImage: "Sentada em lótus, perna estendida, olhar doce" },
    { name: "Tara Branca", symbolicRepresentation: "Roda", symbolicMeaning: "Longevidade e pura", symbolicImage: "Rosto sereno, brilho prateado, três olhos" },
    { name: "Manjushri", symbolicRepresentation: "Espada flamejante", symbolicMeaning: "Sabedoria que corta a ignorância", symbolicImage: "Espada flamejante e pergaminho de sabedoria" },
    { name: "Vajrapani", symbolicRepresentation: "Vajra (raio)", symbolicMeaning: "Força espiritual indomável", symbolicImage: "Corpo azul, raios elétricos e expressão feroz" },
    { name: "Padmasambhava (Guru Rinpoche)", symbolicRepresentation: "Vajra de lótus curvado", symbolicMeaning: "Transformação e poder tântrico", symbolicImage: "Cajado khatvanga, aura dourada, olhar compassivo" },
    { name: "Vajrasattva", symbolicRepresentation: "Diamante (vajra duplo)", symbolicMeaning: "Purificação kármica", symbolicImage: "Corpo branco, segurando vajra e sino" },
    { name: "Amitabha", symbolicRepresentation: "Sol vermelho", symbolicMeaning: "Amor compassivo e renascimento no Paraíso Ocidental", symbolicImage: "Buda vermelho em meditação com lótus e luz rubi" },
    { name: "Akshobhya", symbolicRepresentation: "Espelho azul", symbolicMeaning: "Clareza e imperturbabilidade", symbolicImage: "Buda azul tocando a terra com serenidade" },
    { name: "Ratnasambhava", symbolicRepresentation: "Joia brilhante", symbolicMeaning: "Generosidade e abundância", symbolicImage: "Buda dourado com gesto de dádiva, joias irradiando" },
    { name: "Amoghasiddhi", symbolicRepresentation: "Espada na mar sândalo", symbolicMeaning: "Realização e ação iluminada", symbolicImage: "Buda verde com gesto da coragem, raios em espiral" },
    { name: "Vairochana", symbolicRepresentation: "Moinho circular", symbolicMeaning: "Sabedoria universal", symbolicImage: "Buda branco em trono de leão, brilho de arco-íris" },
    { name: "Kurukulla", symbolicRepresentation: "Arco de flores", symbolicMeaning: "Atração divina e magnetismo", symbolicImage: "Arco de flores, cor vermelha, sorriso sedutor" },
    { name: "Vajrayogini", symbolicRepresentation: "Caveira de yogini", symbolicMeaning: "Superação da morte e do ego", symbolicImage: "Corpo vermelho flamejante, dançando em caveiras" },
    { name: "Hayagriva", symbolicRepresentation: "Cabeça de cavalo na coroa", symbolicMeaning: "Compaixão e poder", symbolicImage: "Cabeça de cavalo surgindo da coroa, chamas ao redor" },
    { name: "Simhamukha", symbolicRepresentation: "Cabeça de leão azul", symbolicMeaning: "Eliminação de energias negativas", symbolicImage: "Cabeça de leoa, rugindo, colar de caveiras" },
    { name: "Ekajati", symbolicRepresentation: "Olho único", symbolicMeaning: "Protetora secreta e vigilante", symbolicImage: "Um olho, um dente, um seio, cabelo em forma de pilar de fogo" },
    { name: "Mahakala", symbolicRepresentation: "Tambor ritual ou tridente", symbolicMeaning: "Guardião feroz da prática", symbolicImage: "Negro com expressão feroz, manto de peles, olhos flamejantes" },
    { name: "Palden Lhamo", symbolicRepresentation: "Sol e lua nos olhos da mula", symbolicMeaning: "Guardiã do carma e dos reinos", symbolicImage: "Mulher azul cavalgando mula com sol e lua nos olhos" },
    { name: "Dorje Drölö", symbolicRepresentation: "Tigre siberiano", symbolicMeaning: "Poder selvagem e transformação súbita", symbolicImage: "Montado em um tigre, expressão irada" },
    { name: "Red Tara", symbolicRepresentation: "Coruja flamejante", symbolicMeaning: "Poder de amor mais paixão iluminada", symbolicImage: "Corpo vermelho, segurando arco e flecha de flores, atraindo o bem" },
    { name: "Black Chakrasamvara", symbolicRepresentation: "Tigre negro", symbolicMeaning: "Prosperidade sem domínio dos outros", symbolicImage: "Dança irada, corpo negro, cercado por chamas" },
    { name: "White Chakrasamvara", symbolicRepresentation: "Vaso de elixir", symbolicMeaning: "Abundância para os compassivos", symbolicImage: "Corpo branco, em união, segurando vaso" },
    { name: "Guhyasamaja", symbolicRepresentation: "Roda de lótus azul", symbolicMeaning: "União de sabedoria e método", symbolicImage: "Corpo azul escuro em união com Sparshavajra, segurando vajra e sino" },
    { name: "Chakrasamvara", symbolicRepresentation: "Roda de osso e cores", symbolicMeaning: "Sabedoria e roda da liberação", symbolicImage: "União com Vajravarahi, roda de luz" },
    { name: "Kalachakra", symbolicRepresentation: "Símbolo de tempo", symbolicMeaning: "Controlar sobre o tempo e consciência unificada", symbolicImage: "Figura multicolorida com 24 braços, em união com Vishvamata" },
    { name: "Hevajra", symbolicRepresentation: "Cálice sorridente", symbolicMeaning: "Transformação da dualidade e dos venenos", symbolicImage: "Dançando em união com Nairatmya, múltiplos braços com armas" },
    { name: "Vajravarahi", symbolicRepresentation: "Cálice com fogo", symbolicMeaning: "Sabedoria transcendente do desejo", symbolicImage: "Mulher vermelha com cabeça de porca no alto da testa" },
    { name: "Yamantaka", symbolicRepresentation: "Cetro real pontudo", symbolicMeaning: "Sabedoria primordial da morte", symbolicImage: "Cabeça de boi, coroa de crânios, olhos de fogo" },
    { name: "Vajra Tangal", symbolicRepresentation: "Tigre de obsidiana", symbolicMeaning: "Sabedoria e realização ferozes", symbolicImage: "Guerreiro irado com armadura, montado em tigre" },
    { name: "Mahattari", symbolicRepresentation: "Arco e flecha", symbolicMeaning: "Reprimir o amor universal", symbolicImage: "Figura feminina com arco e flecha, expressão irada" },
    { name: "Heramba", symbolicRepresentation: "Rato e laranja", symbolicMeaning: "Rei justo e destruição do mal", symbolicImage: "Cinco cabeças, montado em um leão" },
    { name: "Mandala", symbolicRepresentation: "Rosas brancas com espinhos", symbolicMeaning: "Sabedoria dos mundos psíquicos", symbolicImage: "Círculo cósmico com palácios e divindades" },
    { name: "Troma Nagmo", symbolicRepresentation: "Cloud de fumaça", symbolicMeaning: "Destruidora do ego", symbolicImage: "Figura feminina irada, negra, dançando em chamas" },
    { name: "Heruka", symbolicRepresentation: "Cálice duplo com asas", symbolicMeaning: "Êxtase louco e libertação sagrada", symbolicImage: "Figura irada, azul, com asas, em união" },
    { name: "Rahu", symbolicRepresentation: "Cabeça cortada flutuante", symbolicMeaning: "Devorador de ilusões", symbolicImage: "Corpo coberto de olhos, parte inferior de serpente, devorando o sol" },
    { name: "Chinnamasta", symbolicRepresentation: "Cabeça decapitada", symbolicMeaning: "Entrega total e transformação completa", symbolicImage: "Deusa segurando sua própria cabeça, sangue jorrando" },
    { name: "Vajrakilaya", symbolicRepresentation: "Adaga de pontas", symbolicMeaning: "Poder transformador e violento", symbolicImage: "Figura irada com asas, segurando uma phurba (adaga)" },
    { name: "Tilopa", symbolicRepresentation: "Caveira que brilha", symbolicMeaning: "Sabedoria direta e realização direta", symbolicImage: "Yogi em postura de meditação, segurando peixe" },
    { name: "Vajrapani", symbolicRepresentation: "garuda", symbolicMeaning: "Coragem, força e proteção", symbolicImage: "Corpo azul, expressão feroz, segurando um vajra" }
];

export type YidamData = (typeof yidams)[0];
