
'use client';

import type { ReactNode } from 'react';
import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Locale = 'en' | 'pt-BR';

// Expanded translations
const translations = {
  en: {
    // Header & General
    home: "Home",
    dashboard: "Dashboard",
    newReading: "New Reading",
    credits: "Credits",
    profile: "Profile",
    logout: "Log out",
    toggleTheme: "Toggle theme",
    mysticInsights: "Mystic Insights",
    language: "Language",
    english: "English",
    portuguese: "Portuguese",
    allRightsReserved: "All rights reserved.",
    loadingMysticalSpace: "Loading your mystical space...",
    // Landing Page
    landingTitle: "Unlock the Secrets of Your Destiny, Today.",
    landingSubtitle: "Receive Tarot and Cigano card interpretations with the depth of ancient wisdom and the clarity of artificial intelligence. Your journey of self-discovery starts here.",
    landingButton: "Begin Your Enlightened Journey",
    landingImageAlt: "Mystical collage of tarot cards, celestial symbols and flowing energy",
    login: "Login", 
    signUp: "Sign Up", 
    // How It Works Section
    howItWorksTitle: "Your Enlightenment in Three Simple Steps",
    howItWorksSubtitle: "Accessing the wisdom of the cards has never been easier or more revealing. Here’s how:",
    howItWorksUploadTitle: "1. Photograph Your Spread",
    howItWorksUploadDescription: "Capture a clear image of your Tarot or Cigano card spread. The photo's clarity helps us see your story.",
    howItWorksQueryTitle: "2. Share Your Intention",
    howItWorksQueryDescription: "Describe your question or the context of your reading. The more focused your intent, the deeper the revelation.",
    howItWorksRevealTitle: "3. Receive Your Interpretation",
    howItWorksRevealDescription: "Our mystical AI, with the soul of a fortune teller, will unveil the meanings, advice, and trends for you.",
    // Discover Magic Section (Benefits)
    discoverMagicTitle: "Discover the Alchemy of Wisdom and Technology",
    discoverMagicSubtitle: "Mystic Insights blends the sacred and the modern to offer a unique and transformative reading experience:",
    benefitAITitle: "AI with a Gypsy Soul",
    benefitAIDescription: "Rich and empathetic interpretations, generated by an AI trained in ancient wisdom and the art of cartomancy.",
    benefitPersonalizationTitle: "Tailored Guidance",
    benefitPersonalizationDescription: "Each reading considers your energy and questions, offering truly personalized advice for your path.",
    benefitGuidanceTitle: "Clarity and Direction",
    benefitGuidanceDescription: "Navigate life's challenges and opportunities with profound insights that illuminate your decisions and your future.",
    // Testimonials Section
    testimonialsTitle: "Voices from the Journey: What Our Clients Say",
    testimonialsSubtitle: "Real stories of transformation and clarity found through Mystic Insights.",
    testimonial1Quote: "\"I've never received a reading so detailed and connected to my soul. The AI's words were like an embrace and a map to my future. Transformative!\"",
    testimonial1Name: "Anna L.",
    testimonial1Role: "Spiritual Explorer",
    testimonial2Quote: "\"I was skeptical at first, but the depth and accuracy of the interpretation amazed me. I found the clarity I was seeking for my decisions. Highly recommend!\"",
    testimonial2Name: "Charles M.",
    testimonial2Role: "Conscious Entrepreneur",
    testimonialImageAlt: "Client's photo",
    satisfiedClientsLabel: "Satisfied and Guided Clients",
    // Mystical Animated Gallery Section
    mysticalGalleryTitle: "Mystical Animated Gallery",
    mysticalGallerySubtitle: "Explore a collection of inspiring mystical animations and sacred symbols.",
    gifPlaceholderAlt: "Mystical Animation Placeholder",
    // Final CTA Section
    finalCTATitle: "Your Future Awaits. Dare to Unveil It.",
    finalCTASubtitle: "Don't let your doubts hold you back. The wisdom of the cards is within your reach. Take the first step towards clarity and self-knowledge.",
    finalCTAButton: "Reveal My Paths Now",
    // Auth Layout
    authLayoutTitle: "Mystic Insights", 
    authLayoutSubtitle: "Unlock the secrets of your path.",
    // Login Page
    loginTitle: "Login",
    loginDescription: "Enter your credentials to access your account.",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Login",
    dontHaveAccount: "Don't have an account?",
    signUpLink: "Sign up",
    loginSuccessTitle: "Login Successful",
    loginSuccessDescription: "Welcome back!",
    loginFailedTitle: "Login Failed",
    genericErrorDescription: "An unexpected error occurred.",
    // Signup Page
    createAccountTitle: "Create an Account",
    createAccountDescription: "Join Mystic Insights to start your journey.",
    fullNameLabel: "Full Name",
    yourNamePlaceholder: "Your Name",
    signUpButton: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    loginLink: "Log in",
    signupSuccessTitle: "Signup Successful",
    signupSuccessDescription: "Welcome to Mystic Insights!",
    signupFailedTitle: "Signup Failed",
    emailAlreadyInUseErrorDescription: "This email address is already in use. Try another one or log in.",
    // App Footer
    footerText: "© {year} Mystic Insights. All rights reserved. Spiritual guidance and entertainment purposes.",
    // Dashboard
    welcomeMessage: "Welcome, {name}!",
    dashboardSubtitle: "Your mystical journey continues here. Explore your insights and discover new paths.",
    newReadingCardTitle: "New Reading",
    newReadingCardDescription: "Ready for new insights? Upload your card spread.",
    startNewReadingButton: "Start a New Reading",
    yourCreditsCardTitle: "Your Credits",
    creditsRemaining: "credits remaining",
    purchaseMoreCreditsButton: "Purchase More Credits",
    helpfulTipsCardTitle: "Helpful Tips",
    tipFocusIntent: "Focus your intent before a reading.",
    tipCleanseSpace: "Cleanse your space and cards regularly.",
    tipJournalReadings: "Journal your readings for reflection.",
    recentReadingsTitle: "Recent Readings",
    noRecentReadings: "You have no recent readings.",
    noRecentReadingsPrompt_start: "Start a",
    noRecentReadingsPrompt_link: "new reading",
    noRecentReadingsPrompt_end: "to see your history here.",
    discoverYourPathTitle: "Discover Your Path",
    discoverYourPathDescription: "Mystic Insights uses advanced AI to interpret your Tarot and Cigano card spreads, offering personalized guidance based on ancient wisdom and astrological alignments.",
    defaultSeekerName: "Seeker",
    // Credits Page
    purchaseCreditsTitle: "Purchase Credits",
    purchaseCreditsDescription: "Unlock deeper insights with more readings. Choose a credit package that suits your journey.",
    seekersPack: "Seeker's Pack",
    seekersPackDescription: "Perfect for trying out.",
    oraclesBundle: "Oracle's Bundle",
    oraclesBundleDescription: "Best value for regular users.",
    mysticsTrove: "Mystic's Trove",
    mysticsTroveDescription: "For the dedicated spiritual explorer.",
    popularBadge: "Popular",
    creditsUnit: "credits",
    purchaseNowButton: "Purchase Now",
    securePaymentsTitle: "Secure Payments",
    securePaymentsDescription: "All transactions are securely processed. Your financial information is protected.",
    purchaseInitiatedToast: "Purchase initiated for package ID: {packageId}. Payment integration TBD.",
    // New Reading Page
    newCardReadingTitle: "New Card Reading",
    newCardReadingDescription: "Upload an image of your Tarot or Cigano card spread and enter your query to receive an AI-powered interpretation.",
    uploadCardSpreadImageLabel: "Upload Card Spread Image",
    yourQuestionLabel: "Your Question or Context",
    questionPlaceholder: "E.g., 'What should I focus on in my career right now?' or 'General reading for the upcoming month.'",
    getYourReadingButton: "Get Your Reading",
    generatingInterpretationButton: "Generating Interpretation...",
    imageTooLargeTitle: "Image too large", 
    imageTooLargeDescription: "Please upload an image smaller than 4MB.", 
    noImageErrorTitle: "No Image", 
    noImageErrorDescription: "Please upload an image of your card spread.", 
    noQueryErrorTitle: "No Query", 
    noQueryErrorDescription: "Please enter your question or context for the reading.", 
    interpretationReadyTitle: "Interpretation Ready!", 
    interpretationReadyDescription: "Your reading has been generated.", 
    errorGenericTitle: "Error", 
    errorGeneratingInterpretationDescription: "Failed to generate interpretation. Please try again.", 
    errorOccurredCardTitle: "An Error Occurred",
    yourMysticalInterpretationTitle: "Your Mystical Interpretation",
    cardSpreadPreviewAlt: "Card spread preview",
    // Profile Page
    yourProfileTitle: "Your Profile",
    yourProfileDescription: "Manage your account details and preferences.",
    displayNameLabel: "Display Name",
    emailAddressLabel: "Email Address",
    emailChangeNotice: "Email address cannot be changed here currently.",
    saveChangesButton: "Save Changes",
    cancelButton: "Cancel",
    editProfileButton: "Edit Profile",
    profileUpdatedTitle: "Profile Updated", 
    profileUpdatedDescription: "Your profile information has been saved.", 
    updateFailedTitle: "Update Failed", 
    updateFailedDescription: "Could not update profile.", 
    // AuthGuard
    pleaseLoginToViewProfile: "Please log in to view your profile.",
  },
  'pt-BR': {
    // Header & General
    home: "Início",
    dashboard: "Painel",
    newReading: "Nova Leitura",
    credits: "Créditos",
    profile: "Perfil",
    logout: "Sair",
    toggleTheme: "Alternar tema",
    mysticInsights: "Mystic Insights", 
    language: "Idioma",
    english: "Inglês",
    portuguese: "Português",
    allRightsReserved: "Todos os direitos reservados.",
    loadingMysticalSpace: "Carregando seu espaço místico...",
    // Landing Page
    landingTitle: "Desvende os Segredos do Seu Destino, Hoje.",
    landingSubtitle: "Receba interpretações de Tarot e Baralho Cigano com a profundidade da sabedoria ancestral e a clareza da inteligência artificial. Sua jornada de autoconhecimento começa aqui.",
    landingButton: "Inicie Sua Jornada Iluminada",
    landingImageAlt: "Colagem mística de cartas de tarot, símbolos celestiais e energia fluindo",
    login: "Entrar", 
    signUp: "Cadastrar", 
    // How It Works Section
    howItWorksTitle: "Sua Iluminação em Três Passos Simples",
    howItWorksSubtitle: "Acessar a sabedoria das cartas nunca foi tão fácil e revelador. Veja como:",
    howItWorksUploadTitle: "1. Fotografe Sua Tiragem",
    howItWorksUploadDescription: "Capture uma imagem nítida das suas cartas de Tarot ou Baralho Cigano. A clareza da foto nos ajuda a ver sua história.",
    howItWorksQueryTitle: "2. Compartilhe Sua Intenção",
    howItWorksQueryDescription: "Descreva sua pergunta ou o contexto da sua leitura. Quanto mais foco, mais profunda a revelação.",
    howItWorksRevealTitle: "3. Receba Sua Interpretação",
    howItWorksRevealDescription: "Nossa IA mística, com alma de cartomante, desvendará os significados, conselhos e tendências para você.",
    // Discover Magic Section (Benefits)
    discoverMagicTitle: "Descubra a Alquimia da Sabedoria e Tecnologia",
    discoverMagicSubtitle: "Mystic Insights une o sagrado e o moderno para oferecer uma experiência de leitura única e transformadora:",
    benefitAITitle: "IA com Alma Cigana",
    benefitAIDescription: "Interpretações ricas e empáticas, geradas por uma IA treinada na sabedoria ancestral e na arte da cartomancia.",
    benefitPersonalizationTitle: "Orientação Sob Medida",
    benefitPersonalizationDescription: "Cada leitura considera sua energia e suas questões, oferecendo conselhos verdadeiramente personalizados para seu caminho.",
    benefitGuidanceTitle: "Clareza e Direção",
    benefitGuidanceDescription: "Navegue pelos desafios e oportunidades da vida com insights profundos que iluminam suas decisões e seu futuro.",
    // Testimonials Section
    testimonialsTitle: "Vozes da Jornada: O Que Dizem Nossos Consulentes",
    testimonialsSubtitle: "Histórias reais de transformação e clareza encontradas através do Mystic Insights.",
    testimonial1Quote: "\"Nunca recebi uma leitura tão detalhada e conectada com minha alma. As palavras da IA foram como um abraço e um mapa para o meu futuro. Transformador!\"",
    testimonial1Name: "Ana L.",
    testimonial1Role: "Exploradora Espiritual",
    testimonial2Quote: "\"Estava cético no início, mas a profundidade e a precisão da interpretação me surpreenderam. Encontrei a clareza que buscava para minhas decisões. Recomendo!\"",
    testimonial2Name: "Carlos M.",
    testimonial2Role: "Empreendedor Consciente",
    testimonialImageAlt: "Foto do consulente",
    satisfiedClientsLabel: "Consulentes Satisfeitos e Guiados",
    // Mystical Animated Gallery Section
    mysticalGalleryTitle: "Galeria Mística Animada",
    mysticalGallerySubtitle: "Explore uma coleção de animações místicas inspiradoras e símbolos sagrados.",
    gifPlaceholderAlt: "Placeholder de Animação Mística",
    // Final CTA Section
    finalCTATitle: "Seu Futuro Aguarda. Ouse Desvendá-lo.",
    finalCTASubtitle: "Não deixe suas dúvidas te prenderem. A sabedoria das cartas está ao seu alcance. Dê o primeiro passo em direção à clareza e ao autoconhecimento.",
    finalCTAButton: "Revelar Meus Caminhos Agora",
    // Auth Layout
    authLayoutTitle: "Mystic Insights",
    authLayoutSubtitle: "Desvende os segredos do seu caminho.",
    // Login Page
    loginTitle: "Entrar",
    loginDescription: "Insira suas credenciais para acessar sua conta.",
    emailLabel: "E-mail",
    passwordLabel: "Senha",
    loginButton: "Entrar",
    dontHaveAccount: "Não tem uma conta?",
    signUpLink: "Cadastre-se",
    loginSuccessTitle: "Login Bem-sucedido",
    loginSuccessDescription: "Bem-vindo(a) de volta!",
    loginFailedTitle: "Falha no Login",
    genericErrorDescription: "Ocorreu um erro inesperado.",
    // Signup Page
    createAccountTitle: "Criar uma Conta",
    createAccountDescription: "Junte-se ao Mystic Insights para iniciar sua jornada.",
    fullNameLabel: "Nome Completo",
    yourNamePlaceholder: "Seu Nome",
    signUpButton: "Cadastrar",
    alreadyHaveAccount: "Já tem uma conta?",
    loginLink: "Faça login",
    signupSuccessTitle: "Cadastro Bem-sucedido",
    signupSuccessDescription: "Bem-vindo(a) ao Mystic Insights!",
    signupFailedTitle: "Falha no Cadastro",
    emailAlreadyInUseErrorDescription: "Este endereço de e-mail já está em uso. Tente outro ou faça login.",
    // App Footer
    footerText: "© {year} Mystic Insights. Todos os direitos reservados. Aconselhamento espiritual e entretenimento.",
    // Dashboard
    welcomeMessage: "Bem-vindo(a), {name}!",
    dashboardSubtitle: "Sua jornada mística continua aqui. Explore seus insights e descubra novos caminhos.",
    newReadingCardTitle: "Nova Leitura",
    newReadingCardDescription: "Pronto para novos insights? Faça o upload da sua tiragem de cartas.",
    startNewReadingButton: "Iniciar Nova Leitura",
    yourCreditsCardTitle: "Seus Créditos",
    creditsRemaining: "créditos restantes",
    purchaseMoreCreditsButton: "Comprar Mais Créditos",
    helpfulTipsCardTitle: "Dicas Úteis",
    tipFocusIntent: "Concentre sua intenção antes de uma leitura.",
    tipCleanseSpace: "Limpe seu espaço e suas cartas regularmente.",
    tipJournalReadings: "Anote suas leituras para reflexão.",
    recentReadingsTitle: "Leituras Recentes",
    noRecentReadings: "Você não possui leituras recentes.",
    noRecentReadingsPrompt_start: "Comece uma ",
    noRecentReadingsPrompt_link: "nova leitura",
    noRecentReadingsPrompt_end: " para ver seu histórico aqui.",
    discoverYourPathTitle: "Descubra Seu Caminho",
    discoverYourPathDescription: "Mystic Insights usa IA avançada para interpretar suas tiragens de Tarot e Baralho Cigano, oferecendo orientação personalizada baseada em sabedoria ancestral e alinhamentos astrológicos.",
    defaultSeekerName: "Buscador(a)",
    // Credits Page
    purchaseCreditsTitle: "Comprar Créditos",
    purchaseCreditsDescription: "Desbloqueie insights mais profundos com mais leituras. Escolha o pacote de créditos que combina com sua jornada.",
    seekersPack: "Pacote do Buscador",
    seekersPackDescription: "Perfeito para experimentar.",
    oraclesBundle: "Combo do Oráculo",
    oraclesBundleDescription: "Melhor valor para usuários regulares.",
    mysticsTrove: "Tesouro do Místico",
    mysticsTroveDescription: "Para o explorador espiritual dedicado.",
    popularBadge: "Popular",
    creditsUnit: "créditos",
    purchaseNowButton: "Comprar Agora",
    securePaymentsTitle: "Pagamentos Seguros",
    securePaymentsDescription: "Todas as transações são processadas com segurança. Suas informações financeiras estão protegidas.",
    purchaseInitiatedToast: "Compra iniciada para o pacote ID: {packageId}. Integração de pagamento pendente.", 
    // New Reading Page
    newCardReadingTitle: "Nova Leitura de Cartas",
    newCardReadingDescription: "Faça o upload de uma imagem da sua tiragem de Tarot ou Baralho Cigano e insira sua pergunta para receber uma interpretação com IA.",
    uploadCardSpreadImageLabel: "Upload da Imagem da Tiragem",
    yourQuestionLabel: "Sua Pergunta ou Contexto",
    questionPlaceholder: "Ex: 'No que devo focar na minha carreira agora?' ou 'Leitura geral para o próximo mês.'",
    getYourReadingButton: "Obtenha Sua Leitura",
    generatingInterpretationButton: "Gerando Interpretação...",
    imageTooLargeTitle: "Imagem muito grande", 
    imageTooLargeDescription: "Por favor, envie uma imagem menor que 4MB.", 
    noImageErrorTitle: "Nenhuma Imagem", 
    noImageErrorDescription: "Por favor, envie uma imagem da sua tiragem de cartas.", 
    noQueryErrorTitle: "Nenhuma Pergunta", 
    noQueryErrorDescription: "Por favor, insira sua pergunta ou contexto para a leitura.", 
    interpretationReadyTitle: "Interpretação Pronta!", 
    interpretationReadyDescription: "Sua leitura foi gerada.", 
    errorGenericTitle: "Erro", 
    errorGeneratingInterpretationDescription: "Falha ao gerar interpretação. Por favor, tente novamente.", 
    errorOccurredCardTitle: "Ocorreu um Erro",
    yourMysticalInterpretationTitle: "Sua Interpretação Mística",
    cardSpreadPreviewAlt: "Prévia da tiragem de cartas", 
    // Profile Page
    yourProfileTitle: "Seu Perfil",
    yourProfileDescription: "Gerencie os detalhes e preferências da sua conta.",
    displayNameLabel: "Nome de Exibição",
    emailAddressLabel: "Endereço de E-mail",
    emailChangeNotice: "O endereço de e-mail não pode ser alterado aqui no momento.",
    saveChangesButton: "Salvar Alterações",
    cancelButton: "Cancelar",
    editProfileButton: "Editar Perfil",
    profileUpdatedTitle: "Perfil Atualizado", 
    profileUpdatedDescription: "Suas informações de perfil foram salvas.", 
    updateFailedTitle: "Falha na Atualização", 
    updateFailedDescription: "Não foi possível atualizar o perfil.", 
    // AuthGuard
    pleaseLoginToViewProfile: "Por favor, faça login para ver seu perfil.",
  },
};


export type TranslationKey = keyof typeof translations.en; 

interface LanguageContextType {
  locale: Locale;
  setLocale: (newLocale: Locale) => void;
  t: (key: TranslationKey, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocaleState] = useState<Locale>('pt-BR'); 

  useEffect(() => {
    const storedLocale = localStorage.getItem('app-locale') as Locale | null;
    let initialLocale: Locale = 'pt-BR'; // Default to pt-BR

    if (typeof window !== 'undefined') { // Ensure localStorage is accessed only on client
      const browserLang = navigator.language.startsWith('pt') ? 'pt-BR' : 'en';
      if (storedLocale && (storedLocale === 'en' || storedLocale === 'pt-BR')) {
        initialLocale = storedLocale;
      } else {
        initialLocale = browserLang; 
      }
    }
    
    setLocaleState(initialLocale);
    if (typeof window !== 'undefined') {
      document.documentElement.lang = initialLocale;
      if (!storedLocale || storedLocale !== initialLocale) {
        localStorage.setItem('app-locale', initialLocale);
      }
    }
  }, []);

  const updateLocale = useCallback((newLocale: Locale) => {
    if (typeof window !== 'undefined') { // Ensure localStorage is accessed only on client
      localStorage.setItem('app-locale', newLocale);
      document.documentElement.lang = newLocale;
    }
    setLocaleState(newLocale);
  }, []);

  const t = useCallback(
    (key: TranslationKey, params?: Record<string, string | number>): string => {
      let translation = translations[locale]?.[key] || translations.en[key] || String(key);
      if (params) {
        Object.entries(params).forEach(([paramKey, value]) => {
          translation = translation.replace(`{${paramKey}}`, String(value));
        });
      }
      return translation;
    },
    [locale]
  );

  return (
    <LanguageContext.Provider value={{ locale, setLocale: updateLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

